first_project/urls.py
from django.urls import path, include
from first_project import views


urlpatterns = [
    path('', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('formpage', views.form_name_view, name='form_name'),
    path('relative/', views.relative, name='relative'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),


]

my_django_stuff/urls.py
from django.contrib import admin

from django.urls import path, include
from first_project import views

urlpatterns = [
    path('', views.index, name='index'),
    path('first_project/', include(('first_project.urls', 'first_project'), namespace='first_project')),
    path('admin/', admin.site.urls),
    path('formpage/', views.form_name_view, name='form_name'),
    path('users/', views.users_view, name='users'),

]

first_project/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
# inherit models from Model class

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    # string representation of models
    def __str__(self):
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    # string representation of models
    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, )
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE, )
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class User(models.Model):
    firstname = models.CharField(max_length=264)
    lastname = models.CharField(max_length=264)
    email = models.CharField(max_length=264)

first_project/forms.py
from django import forms
from django.core import validators

from django.contrib.auth.models import User
from first_project.models import UserProfileInfo


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("Name needs to start with Z")


class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    # address = forms.CharField()
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])


def clean(self, value):
    cleaned_data = self.cleaned_data

    if self._errors:
        self.data['password'] = 'abc'
        raise forms.ValidationError("You have failed validation!")
    else:
        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms
# import the models
from first_project.models import Topic, Webpage, AccessRecord
from first_project.user_form import NewUser
from first_project.forms import UserForm, UserProfileInfoForm

# for login functionality

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext

# Create your views here.
def index1(request):
    # get data from db using models
    webpage_list = AccessRecord.objects.order_by('date')
    # assigning data to dictionary
    date_dict = {'access_records': webpage_list}
    return render(request, 'first_project/index1.html', context=date_dict)


def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("validation success")
            # to print form info when clicked button
            print("Name- " + form.cleaned_data['name'])

    return render(request, 'first_project/form_page.html', {'form': form})


def users_view(request):
    # this code is used when fetch from db and return back
    # user_list = User.Objects.order_by('first_name')
    # user_dict = {"users": user_list}
    # return render(request, "first_project/users.html", context=user_dict)

    form = NewUser()
    if request.method == "POST":
        form = NewUser(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('error in form')

    return render(request, 'first_project/users.html', {'form': form})


'''
def index(request):
    context_dict = {'text': 'hello world', 'number': 500}
    return render(request, 'first_project/index.html', context_dict)
'''


def other(request):
    return render(request, 'first_project/other.html')


def relative(request):
    return render(request, 'first_project/relative_url_template.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_project/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})





def index(request):
    return render(request, 'first_project/indexe.html')


# login functionaliy
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not Active")

        else:
            print("Someone tried to login and failing")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'first_project/login.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You are logged in , Nice!")

templates/first_project/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'first_project:other' %}">Other</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'first_project:relative' %}">Relative</a>
                </li>
            </ul>
        </div>
    </nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>

</body>
</html>

templates/first_project/basee.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li>
                    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a class="navbar-link" href="{% url 'first_project:register' %}">Register</a>
                </li>

                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'first_project:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'first_project:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

<div class="container">
    {% block body_block %}

    {% endblock %}
</div>

</body>
</html>

templates/first_project/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<h1>Fill out the form!</h1>
<div class="container">
    <form  method="POST">
    {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>

</div>
</body>
</html>

templates/first_project/index.html
<!DOCTYPE html>
{% extends 'first_project/base.html' %}
{% block body_block %}
<h1>Welcome to Index page - relative url</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
{% endblock %}

templates/first_project/index1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Guitar Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}">
</head>
<body>

{#<img src="{% static "images/djangoGuitar.jpg" %}" alt="">#}
{#<h1>Here are your access records:</h1>#}
{#<div class="djangtwo" >#}
{#    {% if access_records %}#}
{#        <table>#}
{#            <thead>#}
{#            <th>Site Name</th>#}
{#            <th>Date Accessed</th>#}
{#            </thead>#}
{#            {% for acc in access_records %}#}
{#                <tr>#}
{#                    <td>{{ acc.name }}</td>#}
{#                <td>{{ acc.date }}</td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#        </table>#}
{#    {%  else %}#}
{#        <p> No records found </p>#}
{#    {% endif %}#}
{#</div>#}
<div class="container">
     <div class="jumbotron">
        <h1>Hi, this is the picture of Django !</h1>
     </div>

</div>
<div>
    <a href="/formpage">Form Page</a>
</div>

</body>
</html>

templates/first_project/indexe.html
<!DOCTYPE html>
{% extends 'first_project/basee.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>Django Level Five</h1>
</div>
{% endblock %}

templates/first_project/login.html
<!DOCTYPE html>
{% extends 'first_project/basee.html' %}
{% block body_block %}
<div class="jumbotron">
<h1>Please Login</h1>
<form method="post" action="{% url 'first_project:login' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="text" name="password" placeholder="Enter Password">

    <input type="submit" name="" value="Login">
</form>
</div>
{% endblock %}

templates/first_project/other.html
<!DOCTYPE html>
{% extends "first_project/base.html" %}
    {% block body_block %}
<h1>Welcome to Other page - relative url</h1>
<h2>This is an example of template inheritence</h2>

    {% endblock %}

templates/first_project/registration.html
<!DOCTYPE html>
{% extends 'first_project/basee.html' %}
{% load static %}
{% block body_block %}
<div class="jumbotron">
{% if registered %}
    <h1>Thanks for registering!</h1>
{% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the Form:</h3>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" value="Register" >
    </form>
{% endif %}
</div>
{% endblock %}

templates/first_project/relative_url_template.html
<!DOCTYPE html>
{% extends 'first_project/base.html' %}
{% block body_block %}
<h1>Welcome to relative url template page - relative url</h1>
<a href="{% url 'first_project:other' %}">The Other page</a>
<br>
<br>
<br>
<a href="{% url 'admin:index' %}">The Admin page</a>
<br>
<br>
<br>
<a href="{% url 'index' %}">The Index page</a>
{% endblock %}

templates/first_project/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>Please sign up here!</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
</div>
</body>
</html>